"""Pr Lifecycle worker mixin."""

from __future__ import annotations

import sys
from typing import Any

from quikode import fsm_runtime
from quikode.agent_registry import make_agent
from quikode.agent_schemas import IntentReviewVerdict, PlannerOutput
from quikode.ancestry import maybe_auto_merge_via_ancestry
from quikode.state import State, SubtaskState
from quikode.state_types import Phase, PrReviewTrigger
from quikode.subtask_schema import PlanValidationError
from quikode.workers.local_ci_capture import capture_local_ci_at_head
from quikode.workers.outcomes import WorkerOutcome
from quikode.workers.planner_driver import _wire_to_runtime_plan


class _TaskWorkerGlobals:
    def __getattr__(self: Any, name: str) -> Any:
        return getattr(sys.modules["quikode.workers.task_worker"], name)


_tw = _TaskWorkerGlobals()
_DEFERRED_PRE_PR_FINDINGS_ARTIFACT = "pre_pr_deferred_findings"


class PrLifecycleWorkerMixin:
    def _open_pr(self: Any) -> WorkerOutcome | None:
        # v3 stacked-diffs fix: rebase + clear parent metadata when the
        # orchestrator flagged a parent-merge before attempting to open the PR.
        rebase_outcome = self._handle_parent_rebase_if_needed()
        if rebase_outcome:
            return rebase_outcome
        fsm_runtime.enter_pr_opening(self.store, self.node.id)
        # Idempotent re-entry: reuse the existing PR if one already exists
        # (prior run that pushed but crashed before transitioning, or
        # daemon orphan-recovery).
        row = self._row()
        if row.get("pr_number") and row.get("pr_url"):
            _tw.log.info(
                "task %s: PR #%s already exists at %s — reusing instead of re-creating",
                self.node.id,
                row["pr_number"],
                row["pr_url"],
            )
            return None
        title = f"{self.node.id}: {self.node.title}"
        body = self._pr_body()
        # v2 Phase C: stacked PR targets the parent branch when _tw.stacking.
        # v3 fix: if the parent merged + GitHub deleted its branch while we
        # were running but the flag wasn't raised in time (e.g. orchestrator
        # missed the merge event), fall back to main via ls-remote check
        # so `gh pr create` doesn't fail with "Base ref must be a branch".
        row_data = dict(row)
        pr_base = str(row_data.get("parent_branch") or self.cfg.base_branch)
        if pr_base != self.cfg.base_branch and not self._remote_branch_exists(pr_base):
            _tw.log.info(
                "task %s: parent branch %s no longer exists on remote (likely merged); "
                "rebasing onto %s and retargeting PR",
                self.node.id,
                pr_base,
                self.cfg.base_branch,
            )
            rebase_ok = self._rebase_inline("main")
            if not rebase_ok:
                raise RuntimeError(
                    f"parent branch {pr_base} deleted; rebase to {self.cfg.base_branch} failed"
                )
            self.store.set_field(self.node.id, parent_branch=None, parent_pr_branch=None)
            pr_base = self.cfg.base_branch
        rc, url, out = _tw.github.open_pr(self._h, title, body, base=pr_base, log_path=self.log_path)
        if rc != 0 or not url:
            raise RuntimeError(f"PR create failed: {out[:300]}")
        m = _tw.re.search(r"/pull/(\d+)", url)
        pr_number = int(m.group(1)) if m else 0
        self.store.set_field(self.node.id, pr_url=url, pr_number=pr_number)
        # Plan 58: PRE_PR_REVIEW → PR_REVIEW at PR open.
        try:
            if str(self._row().get("phase") or "") == Phase.PRE_PR_REVIEW.value:
                self.store.enter_phase(
                    self.node.id,
                    Phase.PR_REVIEW,
                    cycle_in_phase=0,
                    pr_review_trigger=PrReviewTrigger.NONE,
                    note=f"PR opened (#{pr_number}); entering PR_REVIEW phase",
                )
        except Exception as exc:
            _tw.log.warning("phase enter PR_REVIEW failed: %s; continuing", exc)
        return None

    def _remote_branch_exists(self: Any, branch: str) -> bool:
        """Cheap check: does origin still have this branch? Used by _open_pr
        to detect parent-merged-and-deleted before calling `gh pr create`."""
        rc, out = self._git_in_workspace(["ls-remote", "--heads", self.cfg.pr_remote, branch])
        return rc == 0 and bool(out.strip())

    def _pr_body(self: Any) -> str:
        deferred_findings = self._latest_artifact(_DEFERRED_PRE_PR_FINDINGS_ARTIFACT)
        deferred_section = ""
        footer = "_Generated by quikode. Acceptance criteria above were verified by the automated checker before PR open._\n"
        if deferred_findings:
            deferred_section = f"\n\n{deferred_findings[:12000]}\n\n---\n"
            footer = (
                "_Generated by quikode. Local CI and behavior evidence passed before PR open; "
                "deferred quality-audit findings are listed above for human review._\n"
            )
        return (
            f"## Task\n\n"
            f"**{self.node.id}** — {self.node.title}\n\n"
            f"## Scope\n\n{self.node.scope}\n\n"
            f"## Plan\n\n{self.plan_text}\n\n"
            f"---\n\n"
            f"{deferred_section}"
            f"{footer}"
        )

    def _latest_artifact(self: Any, kind: str) -> str | None:
        """Best-effort artifact lookup for PR-body context. Tests and some
        worker doubles do not expose the full Store API, so absence simply
        means no extra PR section.
        """
        conn = getattr(self.store, "conn", None)
        if conn is None:
            return None
        lock = getattr(self.store, "_tx_lock", None)

        def _query() -> Any:
            return conn.execute(
                "SELECT content FROM artifacts WHERE task_id = ? AND kind = ? ORDER BY ts DESC LIMIT 1",
                (self.node.id, kind),
            ).fetchone()

        try:
            if lock is None:
                row = _query()
            else:
                with lock:
                    row = _query()
        except Exception:
            return None
        if row is None:
            return None
        content = row["content"]
        return str(content) if content else None

    def _poll_pr_loop(self: Any) -> WorkerOutcome:
        fsm_runtime.enter_pending_ci(self.store, self.node.id)
        budget = self.cfg.triage_budget_per_phase
        ci_attempts = 0
        while True:
            _tw.time.sleep(20)
            outcome, ci_attempts = self._poll_pr_once(ci_attempts, budget)
            if outcome is not None:
                return outcome

    def _poll_pr_once(self: Any, ci_attempts: int, budget: int) -> tuple[WorkerOutcome | None, int]:
        row = self._row()
        outcome = self._worker_terminal_outcome(row)
        status = None
        if outcome is None:
            row_setup = self._prepare_pr_poll_row(row)
            if isinstance(row_setup, WorkerOutcome):
                outcome = row_setup
            else:
                row = row_setup
                status = self._poll_current_pr(row)
                outcome = self._handle_polled_terminal_status(status)
        if outcome is None and status is not None:
            outcome = self._handle_polled_conflict(status, row)
        if outcome is None and status is not None:
            ci_outcome, ci_attempts, handled = self._handle_polled_ci_failure(
                status, row, ci_attempts, budget
            )
            outcome = ci_outcome if handled else self._green_pr_outcome_or_raise(status, ci_attempts, budget)
        return outcome, ci_attempts

    def _green_pr_outcome_or_raise(
        self: Any, status: Any, ci_attempts: int, budget: int
    ) -> WorkerOutcome | None:
        if ci_attempts >= budget:
            raise RuntimeError("exhausted PR triage budget")
        if status.checks_status not in ("success", "none") or status.mergeable == "CONFLICTING":
            return None
        _tw.sound.ding()
        return WorkerOutcome(State.PENDING_CI)

    def _worker_terminal_outcome(self: Any, row: dict[str, Any]) -> WorkerOutcome | None:
        if row.get("state") in (State.ABORTED.value, State.MERGED.value):
            return WorkerOutcome(State(row["state"]))
        return None

    def _prepare_pr_poll_row(self: Any, row: dict[str, Any]) -> dict[str, Any] | WorkerOutcome:
        rebase_outcome = self._handle_parent_rebase_if_needed()
        if rebase_outcome:
            return rebase_outcome
        row = self._row()
        if not row.get("needs_intent_review"):
            return row
        intent_outcome = self._run_intent_review()
        return intent_outcome if intent_outcome else self._row()

    def _poll_current_pr(self: Any, row: dict[str, Any]) -> Any:
        pr_number = int(_tw.cast(Any, row["pr_number"])) if row.get("pr_number") else 0
        return _tw.github.poll_pr(self.cfg.repo_path, pr_number)

    def _handle_polled_terminal_status(self: Any, status: Any) -> WorkerOutcome | None:
        if status.state == "MERGED":
            fsm_runtime.mark_merged(self.store, self.node.id)
            return WorkerOutcome(State.MERGED)
        if status.state != "CLOSED":
            return None
        return self._handle_closed_polled_pr(status)

    def _handle_closed_polled_pr(self: Any, status: Any) -> WorkerOutcome:
        row_now = self._row()
        parent_branch_field = row_now.get("parent_pr_branch") or row_now.get("parent_branch")
        pr_base_ref = status.base_ref_name or ""
        if (
            parent_branch_field
            and pr_base_ref
            and pr_base_ref != self.cfg.base_branch
            and not self._remote_branch_exists(pr_base_ref)
        ):
            _tw.log.info(
                "task %s: PR #%s auto-closed — base %s deleted by parent merge; "
                "rebasing onto main + creating fresh PR via run_rebase_to_main",
                self.node.id,
                row_now.get("pr_number"),
                pr_base_ref,
            )
            return self.run_rebase_to_main()
        # Plan 56: before treating closed-not-merged as ABORTED, check
        # whether the task's commits are already reachable from origin/main
        # (release-batch integration pattern where the operator pushed an
        # integration branch to main + closed PRs without GH's merge button).
        # The shared helper handles the cfg-flag check, the branch-missing
        # fall-through, the fetch+ancestry primitive, and the FSM dispatch.
        if maybe_auto_merge_via_ancestry(
            cfg=self.cfg,
            store=self.store,
            task_id=self.node.id,
            row_now=row_now,
            run_git=self._git_in_workspace,
        ):
            return WorkerOutcome(State.MERGED)
        fsm_runtime.pr_closed(self.store, self.node.id, note="PR was closed")
        return WorkerOutcome(State.ABORTED)

    def _handle_polled_conflict(self: Any, status: Any, row: dict[str, Any]) -> WorkerOutcome | None:
        retries = int(_tw.cast(Any, row.get("conflict_resolve_retries") or 0))
        if (
            status.mergeable != "CONFLICTING"
            or not self.cfg.conflict_auto_resolve
            or retries >= self.cfg.rebase_max_attempts
        ):
            return None
        rebase_outcome = self._rebase_or_resolve()
        if rebase_outcome:
            return rebase_outcome
        fsm_runtime.enter_pending_ci(self.store, self.node.id, note="back to polling after rebase")
        return None

    def _handle_polled_ci_failure(
        self: Any,
        status: Any,
        row: dict[str, Any],
        ci_attempts: int,
        budget: int,
    ) -> tuple[WorkerOutcome | None, int, bool]:
        """Plan 58: post-PR CI failure detected via the poll loop. Delegate
        to the unified audit driver via the FeedbackWorkerMixin entry
        point (`run_ci_fix_response`) — same code path as the daemon's
        review-watcher tick uses.

        Returns `(outcome, ci_attempts, handled)`. When `handled=True` and
        `outcome=None` the poll loop continues; when `outcome` is set
        the loop exits with that outcome.
        """
        if status.checks_status != "failure" or ci_attempts >= budget:
            return None, ci_attempts, False
        ci_attempts += 1
        # The unified audit driver handles the full fixup → re-audit →
        # commit + push → PENDING_CI cycle. After it returns we're back
        # at PENDING_CI (or BLOCKED) — the poll loop's caller treats
        # PENDING_CI as "keep polling".
        outcome = self.run_ci_fix_response(status)
        if outcome.final_state == State.BLOCKED:
            return outcome, ci_attempts, True
        return None, ci_attempts, True

    def _capture_local_ci_at_head(self: Any) -> tuple[bool, str] | None:
        """Plan 53: thin shim over
        `quikode.workers.local_ci_capture.capture_local_ci_at_head`.
        Kept on the mixin so call sites read as method calls; the body
        lives in the standalone helper module so `pr_lifecycle.py`
        stays under the 600-line architecture budget."""
        return capture_local_ci_at_head(self, _tw)

    def _run_intent_review(self: Any) -> WorkerOutcome | None:
        """A dependency merged. Check if main has shifted under us in a way
        that breaks intent. Per verdict: continue / rebase / block."""
        row = self._row()
        if self._intent_review_budget_exhausted(row):
            return None
        # Plan 28: TRIAGING_FEEDBACK retired. Intent review runs host-side and
        # is bounded; the task stays in its current post-PR state during the
        # check. The outcome handler transitions to PENDING_CI / FIXUP / etc.
        window = self._intent_review_window(row)
        if window is None:
            return None
        base, current_main = window
        _, task_diff = self._git_in_workspace(["diff", f"{base}...HEAD", "--no-color"])
        _, main_log = self._git_in_workspace(["log", "--oneline", f"{base}..{current_main}"])
        _, main_diff = self._git_in_workspace(["diff", f"{base}..{current_main}", "--no-color"])
        outcome = self._run_intent_reviewer(base, current_main, task_diff, main_log, main_diff)
        self.store.clear_intent_review_flag(self.node.id)
        self.store.set_field(self.node.id, last_synced_main_sha=current_main)
        return self._handle_intent_review_outcome(outcome)

    def _intent_review_budget_exhausted(self: Any, row: dict[str, Any]) -> bool:
        budget = self.cfg.intent_max_reviews_per_task
        if int(_tw.cast(Any, row.get("intent_review_count") or 0)) < budget:
            return False
        _tw.log.warning("task %s exhausted intent review budget; clearing flag and proceeding", self.node.id)
        self.store.clear_intent_review_flag(self.node.id)
        return True

    def _intent_review_window(self: Any, row: dict[str, Any]) -> tuple[str, str] | None:
        self._git_in_workspace(["fetch", self.cfg.pr_remote, self.cfg.base_branch])
        base = row.get("last_synced_main_sha") or row.get("base_ref_sha")
        if not base:
            self.store.clear_intent_review_flag(self.node.id)
            fsm_runtime.enter_pending_ci(self.store, self.node.id, note="no base sha; skipping intent review")
            return None
        _, current_main = self._git_in_workspace(
            ["rev-parse", f"{self.cfg.pr_remote}/{self.cfg.base_branch}"]
        )
        current_main = current_main.strip()
        if current_main == base:
            self.store.clear_intent_review_flag(self.node.id)
            fsm_runtime.enter_pending_ci(self.store, self.node.id, note="main unchanged; no review needed")
            return None
        return str(base), current_main

    def _run_intent_reviewer(
        self: Any,
        base: str,
        current_main: str,
        task_diff: str,
        main_log: str,
        main_diff: str,
    ) -> IntentReviewVerdict:
        agent = make_agent("intent_reviewer", self.cfg)
        prompt = _tw.prompts.intent_reviewer_prompt(
            self.cfg,
            self.node,
            task_diff_excerpt=task_diff,
            main_log_excerpt=main_log,
            main_diff_excerpt=main_diff,
        )
        self._write_log_header("INTENT REVIEW", prompt)
        call_id = self.store.record_agent_call_started(
            self.node.id,
            phase="intent_reviewer",
            cli="json_agent",
            model=self.cfg.intent_reviewer_model,
        )
        result = agent.invoke(
            prompt,
            handle=self._h,
            log_path=self.log_path,
            timeout=self.cfg.intent_reviewer_timeout_s,
        )
        self.store.record_agent_call_finished(
            call_id,
            rc=result.rc,
            duration_s=result.duration_s or 0,
            tokens_input=result.tokens_input,
            tokens_output=result.tokens_output,
            cost_usd=result.cost_usd,
        )
        if result.rc != 0 or result.parse_errors or not isinstance(result.structured, IntentReviewVerdict):
            # Plan 38 PR-B.7: a parse failure or transport error here is the
            # safe-no-op equivalent of the prior `default → NO_DRIFT` path —
            # the reviewer is advisory; we surface a synthetic no_drift
            # verdict so the worker continues polling instead of BLOCKing.
            errs = "; ".join(result.parse_errors) if result.parse_errors else f"rc={result.rc}"
            _tw.log.warning(
                "task %s: intent reviewer call failed (%s); defaulting to no_drift",
                self.node.id,
                errs[:300],
            )
            synthetic = IntentReviewVerdict(
                verdict="no_drift",
                affected_areas=[],
                explanation=f"intent reviewer call failed: {errs[:500]}",
                next_actions=[],
            )
            self.store.record_intent_review(
                self.node.id,
                triggered_by_merge_of=None,
                main_sha_before=str(base) if base else None,
                main_sha_after=current_main,
                verdict=synthetic.verdict,
                explanation=synthetic.explanation,
                affected_areas=", ".join(synthetic.affected_areas),
                raw_output=result.raw_text or "",
            )
            return synthetic
        verdict = result.structured
        self.store.record_intent_review(
            self.node.id,
            triggered_by_merge_of=None,
            main_sha_before=str(base) if base else None,
            main_sha_after=current_main,
            verdict=verdict.verdict,
            explanation=verdict.explanation,
            affected_areas=", ".join(verdict.affected_areas),
            raw_output=result.raw_text or verdict.model_dump_json(),
        )
        return verdict

    def _handle_intent_review_outcome(self: Any, outcome: IntentReviewVerdict) -> WorkerOutcome | None:
        if outcome.verdict == "no_drift":
            fsm_runtime.enter_pending_ci(self.store, self.node.id, note="intent review: NO_DRIFT")
            return None
        if outcome.verdict == "minor_drift":
            _tw.log.info(
                "task %s intent review: MINOR_DRIFT — %s",
                self.node.id,
                outcome.explanation[:200],
            )
            return self._rebase_or_resolve()
        _tw.log.warning(
            "task %s intent review: INTENT_CONFLICT — %s",
            self.node.id,
            outcome.explanation[:200],
        )
        replan_count = (self.store.get(self.node.id) or {}).get("replan_count") or 0
        if replan_count >= self.cfg.intent_max_replans:
            fsm_runtime.block_current(
                self.store,
                self.node.id,
                note=f"intent conflict + replan budget exhausted: {outcome.explanation[:300]}",
                last_error=f"INTENT_CONFLICT: {outcome.explanation[:500]}",
            )
            return WorkerOutcome(State.BLOCKED, "intent conflict; replan budget exhausted")
        affected = ", ".join(outcome.affected_areas)
        return self._replan_and_resume(outcome.explanation, affected)

    def _replan_and_resume(self: Any, prior_explanation: str, affected: str) -> WorkerOutcome | None:
        """Plan 58: enter the audit cycle (so block events have a valid
        source state); then replan the spec subtasks."""
        _tw.log.info(
            "task %s: replan-and-resume triggered by intent conflict: %s",
            self.node.id,
            affected[:120],
        )
        # Plan 58: bridge to AUDIT_LOCAL_CI so block_current has a valid source.
        # Intent reviewer fires from PENDING_CI or AWAITING_REVIEW; CI_FIXUP
        # entry accepts both.
        fsm_runtime.enter_audit_cycle_for_ci_fixup(
            self.store,
            self.node.id,
            note=f"replan triggered by intent conflict: {affected[:120]}",
        )
        agent = make_agent("replan_planner", self.cfg)
        contract = self._evaluation_contract()
        prompt = _tw.prompts.planner_prompt(self.cfg, self.dag, self.node, contract)
        # Augment with replan context
        existing_subtasks = self.store.list_subtasks(self.node.id)
        done_summary = "\n".join(
            f"- {s['subtask_id']} ({s['state']}): {s.get('title') or ''}" for s in existing_subtasks
        )
        prompt += (
            "\n\n## REPLAN CONTEXT\n\n"
            "An earlier plan was emitted and partially executed; the world has shifted "
            f"on main since then. The intent reviewer flagged: **{prior_explanation}**\n\n"
            "### Previously emitted subtasks\n"
            f"{done_summary}\n\n"
            "Re-emit a structured plan that:\n"
            "1. **Preserves DONE subtasks** — list them again with their existing IDs and acceptance, so we don't redo them.\n"
            "2. **Replaces or removes** subtasks that are no longer needed because main supplied them.\n"
            "3. **Adds new subtasks** for anything the world-shift now requires (e.g., main added a new instance of a pattern; this task must apply the new pattern there too).\n\n"
            "Emit the SAME structured JSON schema as the spec planner."
        )
        self._write_log_header("PLANNER (replan)", prompt)
        call_id = self.store.record_agent_call_started(
            self.node.id,
            phase="planner_replan",
            cli="json_agent",
            model=self.cfg.replan_planner_model,
        )
        result = agent.invoke(
            prompt,
            handle=self._h,
            log_path=self.log_path,
            timeout=self.cfg.replan_planner_timeout_s,
        )
        self.store.record_agent_call_finished(
            call_id,
            rc=result.rc,
            duration_s=result.duration_s or 0,
            tokens_input=result.tokens_input,
            tokens_output=result.tokens_output,
            cost_usd=result.cost_usd,
        )
        plan_text = result.raw_text or (
            result.structured.model_dump_json() if result.structured is not None else ""
        )
        if plan_text:
            self.store.add_artifact(self.node.id, "planner_replan_output", plan_text)
        if result.rc != 0:
            fsm_runtime.block_current(
                self.store,
                self.node.id,
                note=f"replan agent exited rc={result.rc}: {(result.stderr_excerpt or '')[:300]}",
            )
            return WorkerOutcome(State.BLOCKED, "replan failed")
        if result.parse_errors or not isinstance(result.structured, PlannerOutput):
            errs = "; ".join(result.parse_errors) if result.parse_errors else "no structured output"
            fsm_runtime.block_current(
                self.store,
                self.node.id,
                note=f"replan parse failed: {errs[:500]}",
            )
            return WorkerOutcome(State.BLOCKED, "replan output unparseable")
        self.plan_text = plan_text
        self.store.set_field(self.node.id, plan_text=self.plan_text)
        try:
            new_plan = _wire_to_runtime_plan(
                result.structured,
                expected_node_id=self.node.id,
                spec_gate_command=self.cfg.local_ci_command,
                rubric_categories=list(self.cfg.pre_pr_rubric_categories or []),
                rubric_min_score=int(self.cfg.pre_pr_rubric_min_score),
            )
        except PlanValidationError as e:
            fsm_runtime.block_current(self.store, self.node.id, note=f"replan parse failed: {e}")
            return WorkerOutcome(State.BLOCKED, "replan output unparseable")

        # Persist new subtasks; merge state from prior DONE subtasks where ids match.
        # Plan 52: replan output is always its own planning cycle. We tag
        # rows with kind="replan" and bump the cycle to one past whatever
        # was already on disk, so `qk replan-cycle` can target this set
        # specifically instead of the spec subtasks `upsert_subtasks`
        # otherwise would have replaced wholesale.
        prior_done = {s["subtask_id"]: s for s in existing_subtasks if s["state"] == SubtaskState.DONE.value}
        prior_max_cycle = max(
            (int(r.get("planning_cycle") or 1) for r in existing_subtasks),
            default=0,
        )
        replan_cycle = prior_max_cycle + 1
        new_rows = []
        for s in new_plan.subtasks:
            row = {
                "subtask_id": s.id,
                "title": s.title,
                "depends_on": list(s.depends_on),
                "files_to_touch": list(s.files_to_touch),
                "boundary": s.boundary,
                "acceptance": list(s.acceptance),
                "notes": s.notes,
            }
            new_rows.append(row)
        self.store.upsert_subtasks(
            self.node.id,
            new_rows,
            planning_cycle=replan_cycle,
            planning_kind="replan",
        )
        # Restore DONE state on subtasks whose ids carried over from the old plan
        for sid in prior_done:
            if sid in {s.id for s in new_plan.subtasks}:
                self.store.update_subtask(self.node.id, sid, state=SubtaskState.DONE.value)
        self.plan = new_plan
        # bump replan counter
        with self.store.tx() as c:
            c.execute(
                "UPDATE tasks SET replan_count = COALESCE(replan_count, 0) + 1, updated_at = ? WHERE id = ?",
                (_tw.time.time(), self.node.id),
            )
        _tw.log.info(
            "task %s replanned: %d subtasks (%d carried-over DONE)",
            self.node.id,
            len(new_plan.subtasks),
            len(prior_done),
        )
        # Resume the subtask loop — it skips DONE subtasks implicitly and
        # drives any remaining ones through the same per-subtask flow as
        # the initial run, including progress-check + retry classification.
        outcome = self._subtask_loop()
        if outcome:
            return outcome
        # Resumed fine — fall back into the polling loop.
        fsm_runtime.enter_pending_ci(self.store, self.node.id, note="post-replan; back to polling")
        return None
